os:
  - linux
  - osx
  - windows
sudo: required

language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  # Node 12 is blocked by https://github.com/OpenZWave/node-openzwave-shared/issues/280
  # - '12'
  # - 'node'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s `which node` `which node`js; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then which nodejs || which node; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CC=clang++; export CXX=clang++; export CXXFLAGS=-std=c++11; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink pkg-config; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.9; CC=gcc-4.9; fi'
  - npm install -g node-gyp
install:
  - npm install --unsafe-perm
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
script:
  # Package tests fail for now because materialize is not supported
  # - npm run test:package
  - npm run test:unit
  - export DEBUG=testing:*
  - npm run test:integration
